## Human Expert Baseline

In [2]:
import pandas as pd

In [40]:
df = pd.read_csv('data/random_sequences/ratings.csv', sep=';')
df

Subject  Code  Pain  CASPER  PHA
0         4   152     1     1.0  1.0
1         2   177     0     0.0  1.0
2         3   179     0     0.0  0.0
3         1   197     0     0.0  1.0
4         4   198     0     1.0  1.0
5         2   217     0     0.0  0.0
6         2   257     0     1.0  NaN
7         1   262     0     1.0  1.0
8         3   266     1     NaN  1.0
9         3   287     0     1.0  0.0
10        6   291     0     1.0  0.0
11        1   341     1     1.0  0.0
12        1   342     1     0.0  0.0
13        6   343     1     0.0  1.0
14        4   347     0     1.0  1.0
15        4   354     1     1.0  NaN
16        5   355     1     1.0  1.0
17        5   361     0     1.0  1.0
18        5   365     0     0.0  1.0
19        6   368     1     1.0  NaN
20        1   379     1     0.0  NaN
21        5   428     1     1.0  0.0
22        2   432     1     1.0  1.0
23        5   461     1     1.0  1.0
24        3   465     0     0.0  0.0
25        3   495     1     1.0  1.0
26        4   518     0     1.0  0.0
27        2   563     1     0.0  0.0
28        4   580     0     NaN  NaN
29        1   587     1     1.0  NaN
30        1   592     1     NaN  NaN
31        2   601     1     1.0  1.0
32        4   603     0     0.0  0.0
33        5   613     1     1.0  0.0
34        6   640     1     1.0  1.0
35        2   668     1     0.0  0.0
36        1   680     0     0.0  0.0
37        1   713     0     1.0  1.0
38        2   717     0     1.0  1.0
39        3   745     1     NaN  NaN
40        1   749     0     1.0  0.0
41        5   778     0     0.0  1.0
42        5   815     1     0.0  0.0
43        6   826     0     NaN  NaN
44        1   829     0     1.0  1.0
45        4   861     0     0.0  0.0
46        3   876     1     1.0  1.0
47        2   887     1     1.0  1.0
48        5   925     0     1.0  0.0
49        1   950     1     NaN  NaN
50        3   954     0     1.0  0.0

In [41]:
per_horse_dfs = []
for i in range(1,7):
    hdf = df.loc[(df['Subject']==i), ('Subject','Pain', 'CASPER', 'PHA') ]
    print(hdf)
    per_horse_dfs.append(hdf)

    Subject  Pain  CASPER  PHA
3         1     0     0.0  1.0
7         1     0     1.0  1.0
11        1     1     1.0  0.0
12        1     1     0.0  0.0
20        1     1     0.0  NaN
29        1     1     1.0  NaN
30        1     1     NaN  NaN
36        1     0     0.0  0.0
37        1     0     1.0  1.0
40        1     0     1.0  0.0
44        1     0     1.0  1.0
49        1     1     NaN  NaN
    Subject  Pain  CASPER  PHA
1         2     0     0.0  1.0
5         2     0     0.0  0.0
6         2     0     1.0  NaN
22        2     1     1.0  1.0
27        2     1     0.0  0.0
31        2     1     1.0  1.0
35        2     1     0.0  0.0
38        2     0     1.0  1.0
47        2     1     1.0  1.0
    Subject  Pain  CASPER  PHA
2         3     0     0.0  0.0
8         3     1     NaN  1.0
9         3     0     1.0  0.0
24        3     0     0.0  0.0
25        3     1     1.0  1.0
39        3     1     NaN  NaN
46        3     1     1.0  1.0
50        3     0     1.0  0.0
    Subj

In [42]:
vets = ['CASPER', 'PHA']

In [9]:
import numpy as np

In [43]:
len(per_horse_dfs)

6

In [78]:
per_horse_score_arrays = []
for i, hdf in enumerate(per_horse_dfs):
    nb_samples = len(hdf)
    #print(nb_samples)
    score_array = np.zeros((nb_samples, len(vets)))
    for v, vet in enumerate(vets):
        #print('v', v)
        #print('vet', vet)
        ind = 0
        for index, row in hdf.iterrows():
            #print('ind', ind)
            #print('row', row['JW'])
            #print('PNP', row['Pain/no pain'])
            #print('vet row', row['PHA'])
            if row['Pain'] == row[vet]:
                score_array[ind, v] = 1
            else:
                score_array[ind, v] = 0
            ind += 1
    #print(score_array)
    per_horse_score_arrays.append(score_array)


[x.shape for x in per_horse_score_arrays]
                

[(12, 2), (9, 2), (8, 2), (8, 2), (9, 2), (5, 2)]

In [79]:
per_horse_score_arrays

[array([[ 1.,  0.],
        [ 0.,  0.],
        [ 1.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 1.,  0.],
        [ 0.,  0.],
        [ 1.,  1.],
        [ 0.,  0.],
        [ 0.,  1.],
        [ 0.,  0.],
        [ 0.,  0.]]), array([[ 1.,  0.],
        [ 1.,  1.],
        [ 0.,  0.],
        [ 1.,  1.],
        [ 0.,  0.],
        [ 1.,  1.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 1.,  1.]]), array([[ 1.,  1.],
        [ 0.,  1.],
        [ 0.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 0.,  0.],
        [ 1.,  1.],
        [ 0.,  1.]]), array([[ 1.,  1.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 1.,  0.],
        [ 0.,  1.],
        [ 0.,  0.],
        [ 1.,  1.],
        [ 1.,  1.]]), array([[ 1.,  1.],
        [ 0.,  0.],
        [ 1.,  0.],
        [ 1.,  0.],
        [ 1.,  1.],
        [ 1.,  0.],
        [ 1.,  0.],
        [ 0.,  0.],
        [ 0.,  1.]]), array([[ 0.,  1.],
        [ 0.,  1.],
        [ 1.,  0.],
        [ 1.,  

In [45]:
def get_score(score_array, vet_ind):
    nb_correct = np.sum(score_array[:, vet_ind])
    #print(nb_correct)
    nb_samples = score_array.shape[0]
    #print(nb_samples)
    score = nb_correct / nb_samples
    #print('score ', score)
    return score

In [81]:
per_horse_scores = []
for h in range(0,6):
    sa = per_horse_score_arrays[h]
    #print('HORSE ', h+1)
    scores = np.zeros(len(vets))
    for v, vet in enumerate(vets):
        score = get_score(sa, v)
        #print('Score of ' + vet + ':')
        scores[v] = score
    #print(scores)
    print('Average: ', np.average(scores))
    per_horse_scores.append(scores)
        

('Average: ', 0.25)
('Average: ', 0.5)
('Average: ', 0.6875)
('Average: ', 0.5)
('Average: ', 0.5)
('Average: ', 0.5)


In [82]:
per_horse_scores

[array([ 0.33333333,  0.16666667]),
 array([ 0.55555556,  0.44444444]),
 array([ 0.5  ,  0.875]),
 array([ 0.5,  0.5]),
 array([ 0.66666667,  0.33333333]),
 array([ 0.4,  0.6])]

In [83]:
per_horse_averages = []
for sc, scores in enumerate(per_horse_scores):
    #print('Average for horse ', sc)
    #print(scores)
    av = np.average(scores)
    print(av)
    per_horse_averages.append(av)

0.25
0.5
0.6875
0.5
0.5
0.5


In [84]:
ultimate_average = np.average(np.asarray(per_horse_averages))
ultimate_average

0.48958333333333331

In [85]:
scores_as_array = np.asarray(per_horse_scores)

In [86]:
scores_as_array

array([[ 0.33333333,  0.16666667],
       [ 0.55555556,  0.44444444],
       [ 0.5       ,  0.875     ],
       [ 0.5       ,  0.5       ],
       [ 0.66666667,  0.33333333],
       [ 0.4       ,  0.6       ]])

In [87]:
for i in range(0,len(vets)):
    print('Average for vet ', vets[i])
    print(np.average(scores_as_array[:,i]))

('Average for vet ', 'CASPER')
0.492592592593
('Average for vet ', 'PHA')
0.486574074074


In [88]:
sums = []
for v in range(0,len(vets)):
    sum = 0
    for h in range(0,6):
        nb_right = np.sum(per_horse_score_arrays[h][:,v])
        sum += nb_right
    sums.append(sum)

### Correct guesses per vet

In [89]:
sums

[25.0, 23.0]

In [90]:
25.0/51.0

0.49019607843137253

In [91]:
23.0/51

0.45098039215686275

In [92]:
y_pnp = df['Pain'].values

In [93]:
def make_column_binary(column):
    y = np.zeros(len(column))
    for e, element in enumerate(column):
        if element == 1:
            value = 1
        else:
            value = 0
        y[e] = value
    return y

In [94]:
y_true = make_column_binary(df['Pain'].values.tolist())
y_PHA = make_column_binary(df['PHA'].values)
y_CASPER = make_column_binary(df['CASPER'].values)
print(y_true)
print(y_PHA)
print(y_CASPER)
print len(y_true), len(y_CASPER), len(y_PHA)

[ 1.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  1.  1.  1.  0.  1.  1.  0.
  0.  1.  1.  1.  1.  1.  0.  1.  0.  1.  0.  1.  1.  1.  0.  1.  1.  1.
  0.  0.  0.  1.  0.  0.  1.  0.  0.  0.  1.  1.  0.  1.  0.]
[ 1.  1.  0.  1.  1.  0.  0.  1.  1.  0.  0.  0.  0.  1.  1.  0.  1.  1.
  1.  0.  0.  0.  1.  1.  0.  1.  0.  0.  0.  0.  0.  1.  0.  0.  1.  0.
  0.  1.  1.  0.  0.  1.  0.  0.  1.  0.  1.  1.  0.  0.  0.]
[ 1.  0.  0.  0.  1.  0.  1.  1.  0.  1.  1.  1.  0.  0.  1.  1.  1.  1.
  0.  1.  0.  1.  1.  1.  0.  1.  1.  0.  0.  1.  0.  1.  0.  1.  1.  0.
  0.  1.  1.  0.  1.  0.  0.  0.  1.  0.  1.  1.  1.  0.  1.]
51 51 51


In [95]:
per_horse_ys = []
names = ['Pain', 'CASPER', 'PHA']
for h in range(0,6):
    hdf = per_horse_dfs[h]
    nb_samples = len(hdf)
    ar = np.zeros((nb_samples, 5))
    for n in range(len(names)):
        vs = hdf[names[n]].values.tolist()
        y = make_column_binary(vs)
        #print y
        ar[:,n] = y
    #print(ar)
    per_horse_ys.append(ar)

In [68]:
from sklearn.metrics import classification_report, confusion_matrix, f1_score

In [101]:
# TOTAL F1-scores

cr_CASPER = classification_report(y_true, y_CASPER)
print(cr_CASPER)

cr_PHA = classification_report(y_true, y_PHA)
print(cr_PHA)

cm_CASPER = confusion_matrix(y_true, y_CASPER)
print(cm_CASPER)
cm_PHA = confusion_matrix(y_true, y_PHA)
print(cm_PHA)


             precision    recall  f1-score   support

        0.0       0.55      0.46      0.50        26
        1.0       0.52      0.60      0.56        25

avg / total       0.53      0.53      0.53        51

             precision    recall  f1-score   support

        0.0       0.52      0.58      0.55        26
        1.0       0.50      0.44      0.47        25

avg / total       0.51      0.51      0.51        51

[[12 14]
 [10 15]]
[[15 11]
 [14 11]]


In [97]:
# f1-scores PER HORSE
len(per_horse_ys)
per_horse_ys[1].shape
# List of 6 arrays of shape (nb_samples, 5)

(9, 5)

In [71]:
horse_fscores = []
averages = []
for h in range(0,6):
    ar = per_horse_ys[h]
    f_scores = []
    y_true = ar[:,0]
    for v in range(1,1+len(vets)):
        y_pred = ar[:,v]
        fscore = f1_score(y_true, y_pred, average='weighted')
        f_scores.append(fscore)
    print f_scores
    print 'Average'
    av = np.average(f_scores)
    print av
    averages.append(av)
    horse_fscores.append(f_scores)



[0.33333333333333331, 0.14285714285714288]
Average
0.238095238095
[0.55555555555555558, 0.55555555555555558]
Average
0.555555555556
[0.5, 0.87301587301587302]
Average
0.686507936508
[0.6428571428571429, 0.64545454545454539]
Average
0.644155844156
[0.65800865800865793, 0.33333333333333337]
Average
0.495670995671
[0.59999999999999998, 0.80000000000000004]
Average
0.7


In [98]:
total_av = np.average(np.asarray(averages))
total_av

0.55333092833092834

In [99]:
np.asarray(horse_fscores)

array([[ 0.33333333,  0.14285714],
       [ 0.55555556,  0.55555556],
       [ 0.5       ,  0.87301587],
       [ 0.64285714,  0.64545455],
       [ 0.65800866,  0.33333333],
       [ 0.6       ,  0.8       ]])

In [100]:
scores_as_array

array([[ 0.33333333,  0.16666667],
       [ 0.55555556,  0.44444444],
       [ 0.5       ,  0.875     ],
       [ 0.5       ,  0.5       ],
       [ 0.66666667,  0.33333333],
       [ 0.4       ,  0.6       ]])