## Human Expert Baseline

In [1]:
import pandas as pd

In [6]:
df = pd.read_csv('../data/human_baseline.csv', sep=';')

In [7]:
per_horse_dfs = []
for i in range(1,7):
    hdf = df.loc[(df['Hest']==i), ('Hest','Pain/no pain', 'JW', 'PHA', 'F', 'JL') ]
    print(hdf)
    per_horse_dfs.append(hdf)

    Hest Pain/no pain       JW      PHA        F       JL
1      1         pain     pain     pain     pain     pain
2      1      no pain  no pain  no pain  no pain  no pain
13     1         pain     pain     pain     pain     pain
19     1      no pain     pain  no pain     pain  no pain
37     1         pain  no pain     pain     pain  no pain
40     1      no pain  no pain     pain     pain  no pain
    Hest Pain/no pain       JW      PHA        F       JL
5      2      no pain  no pain     pain     pain  no pain
10     2         pain     pain     pain     pain  no pain
17     2      no pain  no pain  no pain  no pain  no pain
18     2      no pain  no pain     pain     pain  no pain
22     2         pain     pain     pain     pain  no pain
25     2         pain     pain     pain     pain  no pain
32     2         pain     pain     pain     pain  no pain
45     2         pain     pain     pain     pain  no pain
48     2         pain     pain     pain  no pain  no pain
    Hest Pain/

In [8]:
vets = ['JW', 'PHA', 'F', 'JL']

In [9]:
import numpy as np

In [10]:
len(per_horse_dfs)
type(vets)

list

In [11]:
per_horse_score_arrays = []
for i, hdf in enumerate(per_horse_dfs):
    nb_samples = len(hdf)
    #print(nb_samples)
    score_array = np.zeros((nb_samples, len(vets)))
    for v, vet in enumerate(vets):
        #print('v', v)
        #print('vet', vet)
        ind = 0
        for index, row in hdf.iterrows():
            #print('ind', ind)
            #print('row', row['JW'])
            #print('PNP', row['Pain/no pain'])
            #print('vet row', row['PHA'])
            if row['Pain/no pain'] == row[vet]:
                score_array[ind, v] = 1
            else:
                score_array[ind, v] = 0
            ind += 1
    #print(score_array)
    per_horse_score_arrays.append(score_array)
                

In [12]:
def get_score(score_array, vet_ind):
    nb_correct = np.sum(score_array[:, vet_ind])
    #print(nb_correct)
    nb_samples = score_array.shape[0]
    #print(nb_samples)
    score = nb_correct / nb_samples
    #print('score ', score)
    return score

In [13]:
per_horse_scores = []
for h in range(0,6):
    sa = per_horse_score_arrays[h]
    #print('HORSE ', h+1)
    scores = np.zeros(4)
    for v, vet in enumerate(vets):
        score = get_score(sa, v)
        #print('Score of ' + vet + ':')
        scores[v] = score
    #print(scores)
    print('Average: ', np.average(scores))
    per_horse_scores.append(scores)
        

('Average: ', 0.75)
('Average: ', 0.69444444444444442)
('Average: ', 0.3611111111111111)
('Average: ', 0.75)
('Average: ', 0.47222222222222221)
('Average: ', 0.75)


In [14]:
per_horse_scores

[array([ 0.66666667,  0.83333333,  0.66666667,  0.83333333]),
 array([ 1.        ,  0.77777778,  0.66666667,  0.33333333]),
 array([ 0.55555556,  0.22222222,  0.22222222,  0.44444444]),
 array([ 0.77777778,  0.88888889,  0.88888889,  0.44444444]),
 array([ 0.55555556,  0.44444444,  0.44444444,  0.44444444]),
 array([ 0.88888889,  0.66666667,  0.88888889,  0.55555556])]

In [15]:
per_horse_averages = []
for sc, scores in enumerate(per_horse_scores):
    #print('Average for horse ', sc)
    #print(scores)
    av = np.average(scores)
    print(av)
    per_horse_averages.append(av)

0.75
0.694444444444
0.361111111111
0.75
0.472222222222
0.75


In [16]:
ultimate_average = np.average(np.asarray(per_horse_averages))
ultimate_average

0.62962962962962965

In [17]:
scores_as_array = np.asarray(per_horse_scores)

In [18]:
scores_as_array

array([[ 0.66666667,  0.83333333,  0.66666667,  0.83333333],
       [ 1.        ,  0.77777778,  0.66666667,  0.33333333],
       [ 0.55555556,  0.22222222,  0.22222222,  0.44444444],
       [ 0.77777778,  0.88888889,  0.88888889,  0.44444444],
       [ 0.55555556,  0.44444444,  0.44444444,  0.44444444],
       [ 0.88888889,  0.66666667,  0.88888889,  0.55555556]])

In [19]:
for i in range(0,4):
    print('Average for vet ', vets[i])
    print(np.average(scores_as_array[:,i]))

('Average for vet ', 'JW')
0.740740740741
('Average for vet ', 'PHA')
0.638888888889
('Average for vet ', 'F')
0.62962962963
('Average for vet ', 'JL')
0.509259259259


In [20]:
sums = []
for v in range(0,4):
    sum = 0
    for h in range(0,6):
        nb_right = np.sum(per_horse_score_arrays[h][:,v])
        sum += nb_right
    sums.append(sum)

### Correct guesses per vet

In [21]:
sums

[38.0, 32.0, 32.0, 25.0]

In [22]:
38.0/51.0

0.7450980392156863

In [23]:
32.0/51

0.6274509803921569

In [24]:
y_pnp = df['Pain/no pain'].values

In [25]:
def make_column_binary(column):
    y = np.zeros(len(column))
    for e, element in enumerate(column):
        if element == 'pain':
            value = 1
        else:
            value = 0
        y[e] = value
    return y

In [27]:
y_true = make_column_binary(df['Pain/no pain'].values.tolist())
y_JW = make_column_binary(df['JW'].values)
y_PHA = make_column_binary(df['PHA'].values)
y_F = make_column_binary(df['F'].values)
y_JL = make_column_binary(df['JL'].values)
print(y_JW)
print len(y_true), len(y_JW), len(y_PHA), len(y_JL)

[ 1.  1.  0.  1.  1.  0.  1.  1.  1.  0.  1.  0.  0.  1.  1.  0.  1.  0.
  0.  1.  0.  1.  1.  0.  0.  1.  1.  1.  1.  1.  1.  0.  1.  0.  1.  1.
  1.  0.  1.  0.  0.  1.  1.  0.  1.  1.  1.  1.  1.  1.  1.]
51 51 51 51


In [28]:
per_horse_ys = []
names = ['Pain/no pain', 'JW', 'PHA', 'F', 'JL']
for h in range(0,6):
    hdf = per_horse_dfs[h]
    nb_samples = len(hdf)
    ar = np.zeros((nb_samples, 5))
    for n in range(len(names)):
        vs = hdf[names[n]].values.tolist()
        y = make_column_binary(vs)
        #print y
        ar[:,n] = y
    #print(ar)
    per_horse_ys.append(ar)

In [29]:
from sklearn.metrics import classification_report, confusion_matrix, f1_score

In [30]:
# TOTAL F1-scores

cr_JW = classification_report(y_true, y_JW)
print(cr_JW)

cr_PHA = classification_report(y_true, y_PHA)
print(cr_PHA)

cr_F = classification_report(y_true, y_F)
print(cr_F)

cr_JL = classification_report(y_true, y_JL)
print(cr_JL)

             precision    recall  f1-score   support

        0.0       0.65      0.61      0.63        18
        1.0       0.79      0.82      0.81        33

avg / total       0.74      0.75      0.74        51

             precision    recall  f1-score   support

        0.0       0.48      0.56      0.51        18
        1.0       0.73      0.67      0.70        33

avg / total       0.64      0.63      0.63        51

             precision    recall  f1-score   support

        0.0       0.48      0.56      0.51        18
        1.0       0.73      0.67      0.70        33

avg / total       0.64      0.63      0.63        51

             precision    recall  f1-score   support

        0.0       0.40      0.94      0.57        18
        1.0       0.89      0.24      0.38        33

avg / total       0.72      0.49      0.45        51



In [31]:
# f1-scores PER HORSE
len(per_horse_ys)
per_horse_ys[1].shape
# List of 6 arrays of shape (nb_samples, 5)

(9, 5)

In [32]:
horse_fscores = []
averages = []
for h in range(0,6):
    ar = per_horse_ys[h]
    f_scores = []
    y_true = ar[:,0]
    for v in range(1,5):
        y_pred = ar[:,v]
        fscore = f1_score(y_true, y_pred, average='weighted')
        f_scores.append(fscore)
    print f_scores
    print 'Average'
    av = np.average(f_scores)
    print av
    print 'STDEV'
    std = np.std(f_scores)
    print std
    averages.append(av)
    horse_fscores.append(f_scores)



[0.66666666666666663, 0.82857142857142863, 0.62499999999999989, 0.82857142857142863]
Average
0.737202380952
STDEV
0.0925489964921
[1.0, 0.73809523809523803, 0.64615384615384608, 0.16666666666666666]
Average
0.637728937729
STDEV
0.301365375876
[0.55555555555555558, 0.22222222222222221, 0.22222222222222221, 0.37229437229437223]
Average
0.343073593074
STDEV
0.137124529162
[0.73809523809523803, 0.89177489177489178, 0.89177489177489178, 0.37229437229437223]
Average
0.723484848485
STDEV
0.212244723958
[0.55555555555555558, 0.45887445887445882, 0.45887445887445882, 0.44444444444444442]
Average
0.479437229437
STDEV
0.0443400204078
[0.89177489177489178, 0.67532467532467533, 0.89177489177489178, 0.53333333333333333]
Average
0.748051948052
STDEV
0.152238225168


/Users/sbroome/miniconda2/lib/python2.7/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [36]:
total_av = np.average(np.asarray(averages))
print(total_av)

total_std = np.std(np.asarray(averages))
print(total_std)

0.611496489621
0.151200417652


In [34]:
np.asarray(horse_fscores)

array([[ 0.66666667,  0.82857143,  0.625     ,  0.82857143],
       [ 1.        ,  0.73809524,  0.64615385,  0.16666667],
       [ 0.55555556,  0.22222222,  0.22222222,  0.37229437],
       [ 0.73809524,  0.89177489,  0.89177489,  0.37229437],
       [ 0.55555556,  0.45887446,  0.45887446,  0.44444444],
       [ 0.89177489,  0.67532468,  0.89177489,  0.53333333]])

In [35]:
scores_as_array

array([[ 0.66666667,  0.83333333,  0.66666667,  0.83333333],
       [ 1.        ,  0.77777778,  0.66666667,  0.33333333],
       [ 0.55555556,  0.22222222,  0.22222222,  0.44444444],
       [ 0.77777778,  0.88888889,  0.88888889,  0.44444444],
       [ 0.55555556,  0.44444444,  0.44444444,  0.44444444],
       [ 0.88888889,  0.66666667,  0.88888889,  0.55555556]])