## Human Expert Baseline

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/random_sequences/ratings.csv', sep=';')
df

Subject  Code  Pain  CASPER  PHA  KBG   KA
0         4   152     1     1.0  1.0  1.0  0.0
1         2   177     0     0.0  1.0  1.0  0.0
2         3   179     0     0.0  0.0  0.0  1.0
3         1   197     0     0.0  1.0  0.0  1.0
4         4   198     0     1.0  1.0  0.0  0.0
5         2   217     0     0.0  0.0  NaN  0.0
6         2   257     0     1.0  NaN  1.0  0.0
7         1   262     0     1.0  1.0  1.0  1.0
8         3   266     1     NaN  1.0  NaN  0.0
9         3   287     0     1.0  0.0  0.0  0.0
10        6   291     0     1.0  0.0  1.0  0.0
11        1   341     1     1.0  0.0  1.0  1.0
12        1   342     1     0.0  0.0  0.0  0.0
13        6   343     1     0.0  1.0  1.0  0.0
14        4   347     0     1.0  1.0  1.0  0.0
15        4   354     1     1.0  NaN  1.0  1.0
16        5   355     1     1.0  1.0  1.0  0.0
17        5   361     0     1.0  1.0  0.0  1.0
18        5   365     0     0.0  1.0  1.0  0.0
19        6   368     1     1.0  NaN  1.0  0.0
20        1   379     1     0.0  NaN  1.0  NaN
21        5   428     1     1.0  0.0  0.0  1.0
22        2   432     1     1.0  1.0  1.0  1.0
23        5   461     1     1.0  1.0  1.0  1.0
24        3   465     0     0.0  0.0  NaN  0.0
25        3   495     1     1.0  1.0  1.0  1.0
26        4   518     0     1.0  0.0  0.0  0.0
27        2   563     1     0.0  0.0  1.0  0.0
28        4   580     0     NaN  NaN  NaN  NaN
29        1   587     1     1.0  NaN  1.0  0.0
30        1   592     1     NaN  NaN  1.0  0.0
31        2   601     1     1.0  1.0  1.0  0.0
32        4   603     0     0.0  0.0  0.0  NaN
33        5   613     1     1.0  0.0  1.0  0.0
34        6   640     1     1.0  1.0  1.0  0.0
35        2   668     1     0.0  0.0  1.0  0.0
36        1   680     0     0.0  0.0  0.0  1.0
37        1   713     0     1.0  1.0  1.0  1.0
38        2   717     0     1.0  1.0  1.0  0.0
39        3   745     1     NaN  NaN  1.0  NaN
40        1   749     0     1.0  0.0  0.0  1.0
41        5   778     0     0.0  1.0  0.0  0.0
42        5   815     1     0.0  0.0  1.0  0.0
43        6   826     0     NaN  NaN  NaN  0.0
44        1   829     0     1.0  1.0  1.0  1.0
45        4   861     0     0.0  0.0  1.0  1.0
46        3   876     1     1.0  1.0  1.0  NaN
47        2   887     1     1.0  1.0  1.0  0.0
48        5   925     0     1.0  0.0  0.0  0.0
49        1   950     1     NaN  NaN  NaN  NaN
50        3   954     0     1.0  0.0  0.0  0.0

In [31]:
per_horse_dfs = []
for i in range(1,7):
    hdf = df.loc[(df['Subject']==i), ('Subject','Pain', 'CASPER', 'PHA', 'KBG', 'KA') ]
    print(hdf)
    per_horse_dfs.append(hdf)

    Subject  Pain  CASPER  PHA  KBG   KA
3         1     0     0.0  1.0  0.0  1.0
7         1     0     1.0  1.0  1.0  1.0
11        1     1     1.0  0.0  1.0  1.0
12        1     1     0.0  0.0  0.0  0.0
20        1     1     0.0  NaN  1.0  NaN
29        1     1     1.0  NaN  1.0  0.0
30        1     1     NaN  NaN  1.0  0.0
36        1     0     0.0  0.0  0.0  1.0
37        1     0     1.0  1.0  1.0  1.0
40        1     0     1.0  0.0  0.0  1.0
44        1     0     1.0  1.0  1.0  1.0
49        1     1     NaN  NaN  NaN  NaN
    Subject  Pain  CASPER  PHA  KBG   KA
1         2     0     0.0  1.0  1.0  0.0
5         2     0     0.0  0.0  NaN  0.0
6         2     0     1.0  NaN  1.0  0.0
22        2     1     1.0  1.0  1.0  1.0
27        2     1     0.0  0.0  1.0  0.0
31        2     1     1.0  1.0  1.0  0.0
35        2     1     0.0  0.0  1.0  0.0
38        2     0     1.0  1.0  1.0  0.0
47        2     1     1.0  1.0  1.0  0.0
    Subject  Pain  CASPER  PHA  KBG   KA
2         3     

In [32]:
vets = ['CASPER', 'PHA', 'KBG', 'KA']

In [33]:
import numpy as np

In [34]:
len(per_horse_dfs)

6

In [35]:
per_horse_score_arrays = []
for i, hdf in enumerate(per_horse_dfs):
    nb_samples = len(hdf)
    #print(nb_samples)
    score_array = np.zeros((nb_samples, len(vets)))
    for v, vet in enumerate(vets):
        #print('v', v)
        #print('vet', vet)
        ind = 0
        for index, row in hdf.iterrows():
            #print('ind', ind)
            #print('row', row['JW'])
            #print('PNP', row['Pain/no pain'])
            #print('vet row', row['PHA'])
            if row['Pain'] == row[vet]:
                score_array[ind, v] = 1
            else:
                score_array[ind, v] = 0
            ind += 1
    #print(score_array)
    per_horse_score_arrays.append(score_array)


[x.shape for x in per_horse_score_arrays]
                

[(12, 4), (9, 4), (8, 4), (8, 4), (9, 4), (5, 4)]

In [36]:
per_horse_score_arrays

[array([[ 1.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 1.,  0.,  1.,  1.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 1.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 1.,  1.,  1.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  1.,  1.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]), array([[ 1.,  0.,  0.,  1.],
        [ 1.,  1.,  0.,  1.],
        [ 0.,  0.,  0.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 0.,  0.,  1.,  0.],
        [ 1.,  1.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.],
        [ 1.,  1.,  1.,  0.]]), array([[ 1.,  1.,  1.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  1.,  1.,  1.],
        [ 1.,  1.,  0.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 0.,  0.,  1.,  0.],
        [ 1.,  1.,  1.,  0.],
        [ 0.,  1.,  1.,  1.]]), array([[ 1.,  1.,  1.,  0.],
        [ 0.,  0.,  1.,  1.],
        [ 0.,  0.,  0.,  1.],
        [ 1.,  0.,  1.,  1.],
       

In [37]:
def get_score(score_array, vet_ind):
    nb_correct = np.sum(score_array[:, vet_ind])
    #print(nb_correct)
    nb_samples = score_array.shape[0]
    #print(nb_samples)
    score = nb_correct / nb_samples
    #print('score ', score)
    return score

In [66]:
per_horse_scores = []
for h in range(0,6):
    sa = per_horse_score_arrays[h]
    #print('HORSE ', h+1)
    scores = np.zeros(len(vets))
    for v, vet in enumerate(vets):
        score = get_score(sa, v)
        #print('Score of ' + vet + ':')
        scores[v] = score
    #print(scores)
    print('Average: ', np.average(scores))
    per_horse_scores.append(scores)
        

('Average: ', 0.29166666666666669)
('Average: ', 0.52777777777777779)
('Average: ', 0.65625)
('Average: ', 0.53125)
('Average: ', 0.58333333333333326)
('Average: ', 0.5)


In [67]:
per_horse_scores

[array([ 0.33333333,  0.16666667,  0.58333333,  0.08333333]),
 array([ 0.55555556,  0.44444444,  0.55555556,  0.55555556]),
 array([ 0.5  ,  0.875,  0.75 ,  0.5  ]),
 array([ 0.5  ,  0.5  ,  0.625,  0.5  ]),
 array([ 0.66666667,  0.33333333,  0.77777778,  0.55555556]),
 array([ 0.4,  0.6,  0.6,  0.4])]

In [68]:
per_horse_averages = []
for sc, scores in enumerate(per_horse_scores):
    #print('Average for horse ', sc)
    #print(scores)
    av = np.average(scores)
    print(av)
    per_horse_averages.append(av)

0.291666666667
0.527777777778
0.65625
0.53125
0.583333333333
0.5


In [69]:
ultimate_average = np.average(np.asarray(per_horse_averages))
ultimate_average

0.51504629629629628

In [70]:
scores_as_array = np.asarray(per_horse_scores)

In [71]:
scores_as_array

array([[ 0.33333333,  0.16666667,  0.58333333,  0.08333333],
       [ 0.55555556,  0.44444444,  0.55555556,  0.55555556],
       [ 0.5       ,  0.875     ,  0.75      ,  0.5       ],
       [ 0.5       ,  0.5       ,  0.625     ,  0.5       ],
       [ 0.66666667,  0.33333333,  0.77777778,  0.55555556],
       [ 0.4       ,  0.6       ,  0.6       ,  0.4       ]])

In [72]:
for i in range(0,len(vets)):
    print('Average for vet ', vets[i])
    print(np.average(scores_as_array[:,i]))

('Average for vet ', 'CASPER')
0.492592592593
('Average for vet ', 'PHA')
0.486574074074
('Average for vet ', 'KBG')
0.648611111111
('Average for vet ', 'KA')
0.432407407407


In [73]:
sums = []
for v in range(0,len(vets)):
    sum = 0
    for h in range(0,6):
        nb_right = np.sum(per_horse_score_arrays[h][:,v])
        sum += nb_right
    sums.append(sum)

### Correct guesses per vet

In [74]:
sums

[25.0, 23.0, 33.0, 21.0]

In [75]:
25.0/51.0

0.49019607843137253

In [76]:
23.0/51

0.45098039215686275

In [77]:
y_pnp = df['Pain'].values

In [78]:
def make_column_binary(column):
    y = np.zeros(len(column))
    for e, element in enumerate(column):
        if element == 1:
            value = 1
        else:
            value = 0
        y[e] = value
    return y

In [89]:
y_true = make_column_binary(df['Pain'].values.tolist())
y_PHA = make_column_binary(df['PHA'].values)
y_CASPER = make_column_binary(df['CASPER'].values)
y_KBG = make_column_binary(df['KBG'].values)
y_KA = make_column_binary(df['KA'].values)
print(y_true)
print(y_PHA)
print(y_CASPER)
print len(y_true), len(y_CASPER), len(y_PHA)

[ 1.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  1.  1.  1.  0.  1.  1.  0.
  0.  1.  1.  1.  1.  1.  0.  1.  0.  1.  0.  1.  1.  1.  0.  1.  1.  1.
  0.  0.  0.  1.  0.  0.  1.  0.  0.  0.  1.  1.  0.  1.  0.]
[ 1.  1.  0.  1.  1.  0.  0.  1.  1.  0.  0.  0.  0.  1.  1.  0.  1.  1.
  1.  0.  0.  0.  1.  1.  0.  1.  0.  0.  0.  0.  0.  1.  0.  0.  1.  0.
  0.  1.  1.  0.  0.  1.  0.  0.  1.  0.  1.  1.  0.  0.  0.]
[ 1.  0.  0.  0.  1.  0.  1.  1.  0.  1.  1.  1.  0.  0.  1.  1.  1.  1.
  0.  1.  0.  1.  1.  1.  0.  1.  1.  0.  0.  1.  0.  1.  0.  1.  1.  0.
  0.  1.  1.  0.  1.  0.  0.  0.  1.  0.  1.  1.  1.  0.  1.]
51 51 51


In [90]:
per_horse_ys = []
names = ['Pain', 'CASPER', 'PHA', 'KBG', 'KA']
for h in range(0,6):
    hdf = per_horse_dfs[h]
    nb_samples = len(hdf)
    ar = np.zeros((nb_samples, 5))
    for n in range(len(names)):
        vs = hdf[names[n]].values.tolist()
        y = make_column_binary(vs)
        #print y
        ar[:,n] = y
    #print(ar)
    per_horse_ys.append(ar)

In [91]:
from sklearn.metrics import classification_report, confusion_matrix, f1_score, accuracy_score

In [92]:
# TOTAL F1-scores

cr_CASPER = classification_report(y_true, y_CASPER)
print(cr_CASPER)

cr_PHA = classification_report(y_true, y_PHA)
print(cr_PHA)

cr_KBG = classification_report(y_true, y_KBG)
print(cr_KBG)

cr_KA = classification_report(y_true, y_KA)
print(cr_KA)

cm_CASPER = confusion_matrix(y_true, y_CASPER)
print(cm_CASPER)
cm_PHA = confusion_matrix(y_true, y_PHA)
print(cm_PHA)
cm_KBG = confusion_matrix(y_true, y_KBG)
print(cm_KBG)
cm_KA = confusion_matrix(y_true, y_KA)
print(cm_KA)


             precision    recall  f1-score   support

        0.0       0.55      0.46      0.50        26
        1.0       0.52      0.60      0.56        25

avg / total       0.53      0.53      0.53        51

             precision    recall  f1-score   support

        0.0       0.52      0.58      0.55        26
        1.0       0.50      0.44      0.47        25

avg / total       0.51      0.51      0.51        51

             precision    recall  f1-score   support

        0.0       0.80      0.62      0.70        26
        1.0       0.68      0.84      0.75        25

avg / total       0.74      0.73      0.72        51

             precision    recall  f1-score   support

        0.0       0.47      0.65      0.55        26
        1.0       0.40      0.24      0.30        25

avg / total       0.44      0.45      0.43        51

[[12 14]
 [10 15]]
[[15 11]
 [14 11]]
[[16 10]
 [ 4 21]]
[[17  9]
 [19  6]]


In [97]:
# f1-scores PER HORSE
len(per_horse_ys)
per_horse_ys[1].shape
# List of 6 arrays of shape (nb_samples, 5)

[array([[ 0.,  0.,  1.,  0.,  1.],
        [ 0.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  0.,  1.,  1.],
        [ 1.,  0.,  0.,  0.,  0.],
        [ 1.,  0.,  0.,  1.,  0.],
        [ 1.,  1.,  0.,  1.,  0.],
        [ 1.,  0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  0.,  1.],
        [ 0.,  1.,  1.,  1.,  1.],
        [ 0.,  1.,  0.,  0.,  1.],
        [ 0.,  1.,  1.,  1.,  1.],
        [ 1.,  0.,  0.,  0.,  0.]]), array([[ 0.,  0.,  1.,  1.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  1.,  0.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  0.,  0.,  1.,  0.],
        [ 1.,  1.,  1.,  1.,  0.],
        [ 1.,  0.,  0.,  1.,  0.],
        [ 0.,  1.,  1.,  1.,  0.],
        [ 1.,  1.,  1.,  1.,  0.]]), array([[ 0.,  0.,  0.,  0.,  1.],
        [ 1.,  0.,  1.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  0.,  0.,  1.,  0.],
        [ 1.,  1.,  1.,  1.,  0.],
        [ 0.,  1.,

In [94]:
horse_fscores = []
horse_accs = []
averages = []
averages_accs = []
for h in range(0,6):
    ar = per_horse_ys[h]
    f_scores = []
    accs = []
    y_true = ar[:,0]
    for v in range(1,1+len(vets)):
        y_pred = ar[:,v]
        fscore = f1_score(y_true, y_pred, average='weighted')
        acc = accuracy_score(y_true, y_pred)
        f_scores.append(fscore)
        accs.append(acc)
    print f_scores
    print 'Average'
    av = np.average(f_scores)
    print av
    avacc = np.average(accs)
    averages.append(av)
    averages_accs.append(avacc)
    horse_fscores.append(f_scores)
    horse_accs.append(accs)



[0.33333333333333331, 0.14285714285714288, 0.58041958041958031, 0.076923076923076913]
Average
0.283383283383
[0.55555555555555558, 0.55555555555555558, 0.6051282051282052, 0.48148148148148157]
Average
0.54943019943
[0.5, 0.87301587301587302, 0.87301587301587302, 0.46666666666666667]
Average
0.678174603175
[0.6428571428571429, 0.64545454545454539, 0.76666666666666672, 0.75]
Average
0.701244588745
[0.65800865800865793, 0.33333333333333337, 0.7777777777777779, 0.54444444444444451]
Average
0.578391053391
[0.59999999999999998, 0.80000000000000004, 0.78095238095238084, 0.22857142857142859]
Average
0.602380952381


In [95]:
total_av = np.average(np.asarray(averages))
total_av

0.56550078008411353

In [96]:
total_av_acc = np.average(np.asarray(averages_accs))
total_av_acc

0.58055555555555549

In [99]:
total_av_std_acc = np.std(np.asarray(averages_accs))
total_av_std_acc

0.13611819709446238

In [87]:
np.asarray(horse_fscores)

array([[ 0.33333333,  0.14285714,  0.58041958,  0.07692308],
       [ 0.55555556,  0.55555556,  0.60512821,  0.48148148],
       [ 0.5       ,  0.87301587,  0.87301587,  0.46666667],
       [ 0.64285714,  0.64545455,  0.76666667,  0.75      ],
       [ 0.65800866,  0.33333333,  0.77777778,  0.54444444],
       [ 0.6       ,  0.8       ,  0.78095238,  0.22857143]])

In [88]:
scores_as_array

array([[ 0.33333333,  0.16666667,  0.58333333,  0.08333333],
       [ 0.55555556,  0.44444444,  0.55555556,  0.55555556],
       [ 0.5       ,  0.875     ,  0.75      ,  0.5       ],
       [ 0.5       ,  0.5       ,  0.625     ,  0.5       ],
       [ 0.66666667,  0.33333333,  0.77777778,  0.55555556],
       [ 0.4       ,  0.6       ,  0.6       ,  0.4       ]])